version: '3.7'
services:
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki:/loki
    networks:
      - loki-net
  promtail:
    image: grafana/promtail:latest
    user: root
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./promtail:/tmp
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - loki-net
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - loki-net
networks:
  loki-net: